#![deny(clippy::all, clippy::pedantic, clippy::nursery, dead_code)]

// Include the proto modules that are auto-generated by tonic-build
// DO NOT manually redefine these types - they're generated from .proto files
pub mod xmtp {
    // Core message API
    pub mod message_api {
        pub mod v1 {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.message_api.v1.rs");
        }
    }

    // Message contents (needed by message_api)
    pub mod message_contents {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.message_contents.rs");
    }

    // Identity modules (needed by MLS API)
    pub mod identity {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.identity.rs");

        pub mod associations {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.identity.associations.rs");
        }
    }

    // Device sync modules (needed by MLS message contents)
    pub mod device_sync {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.device_sync.rs");

        pub mod content {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.content.rs");
        }

        pub mod consent_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.consent_backup.rs");
        }

        pub mod event_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.event_backup.rs");
        }

        pub mod group_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.group_backup.rs");
        }

        pub mod message_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.message_backup.rs");
        }
    }

    // MLS API - contains GroupMessage definition
    pub mod mls {
        pub mod api {
            pub mod v1 {
                #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
                include!("generated/xmtp.mls.api.v1.rs");
            }
        }

        // MLS message contents - contains PlaintextEnvelope, EncodedContent, etc.
        pub mod message_contents {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.mls.message_contents.rs");

            pub mod content_types {
                #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
                include!("generated/xmtp.mls.message_contents.content_types.rs");
            }
        }
    }
}

pub mod types;
pub mod utils;
pub mod worker;
