#![deny(clippy::all, clippy::pedantic, clippy::nursery, dead_code)]

// Include the proto modules that are auto-generated by tonic-build
// DO NOT manually redefine these types - they're generated from .proto files
pub mod xmtp {
    // Core message API - DIRECTLY USED for Envelope, MessageApiClient, SubscribeAllRequest
    pub mod message_api {
        pub mod v1 {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.message_api.v1.rs");
        }
    }

    // Message contents - REQUIRED by message_api::v1 for PublicKey, Signature types
    pub mod message_contents {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.message_contents.rs");
    }

    // Identity modules - REQUIRED by mls::api::v1 for RecoverableEd25519Signature
    pub mod identity {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.identity.rs");

        pub mod associations {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.identity.associations.rs");
        }
    }

    // Device sync modules - REQUIRED by mls::message_contents for DeviceSyncRequest/Reply
    // All submodules are needed due to internal dependencies in the generated code
    pub mod device_sync {
        #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
        include!("generated/xmtp.device_sync.rs");

        pub mod content {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.content.rs");
        }

        pub mod consent_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.consent_backup.rs");
        }

        pub mod event_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.event_backup.rs");
        }

        pub mod group_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.group_backup.rs");
        }

        pub mod message_backup {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.device_sync.message_backup.rs");
        }
    }

    // MLS API - DIRECTLY USED for GroupMessage, group_message::V1
    pub mod mls {
        pub mod api {
            pub mod v1 {
                #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
                include!("generated/xmtp.mls.api.v1.rs");
            }
        }

        // MLS message contents - REQUIRED by mls::api::v1 for CommitLogEntry
        pub mod message_contents {
            #![allow(clippy::all, clippy::pedantic, clippy::nursery)]
            include!("generated/xmtp.mls.message_contents.rs");
        }
    }
}

pub mod types;
pub mod worker;
pub mod xmtp_utils;
