[workspace]
members = [
    "servers/backend-server",
    "servers/enclave-server",
    "services/notification-service",
    "services/image-service",
    "services/enclave-service",
    "shared/models",
]
resolver = "2"

[workspace.package]
edition      = "2021"
rust-version = "1.85.0"
version      = "0.1.0"
license      = "MIT"

[workspace.dependencies]
# Web framework
axum       = "0.8.1"
tower      = "0.5.2"
tower-http = { version = "0.6.2", features = ["trace"] }

# Async runtime
tokio = { version = "1.44.1", features = ["full"] }

# Serialization
serde      = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow    = "1.0"
thiserror = "2.0"

# Logging
tracing            = "0.1"
tracing-subscriber = "0.3"

# HTTP
http = "1.1"
