# Clippy configuration

# Set the maximum cognitive complexity allowed
cognitive-complexity-threshold = 30

# Set the maximum number of lines a function can have
too-many-lines-threshold = 100

# Set the maximum number of arguments a function can have
too-many-arguments-threshold = 7

# Set the maximum nesting level
excessive-nesting-threshold = 5

# Enforce MSRV (Minimum Supported Rust Version)
msrv = "1.85.0"
