name: world-chat-backend
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb
      - DISABLE_EVENTS=1
      # Localstack disables signature validation by default, but we need it for testing
      # https://docs.localstack.cloud/aws/capabilities/config/configuration/#s3
      - S3_SKIP_SIGNATURE_VALIDATION=0
    volumes:
      - /var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - "./aws-seed.sh:/etc/localstack/init/ready.d/aws-seed.sh"
