name: world-chat-backend
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sqs
      - DISABLE_EVENTS=1
      # Localstack disables signature validation by default, but we need it for testing
      # https://docs.localstack.cloud/aws/capabilities/config/configuration/#s3
      - S3_SKIP_SIGNATURE_VALIDATION=0
    volumes:
      - /var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - "./aws-seed.sh:/etc/localstack/init/ready.d/aws-seed.sh"
    healthcheck:
      test: |
        curl -s http://localhost:4566/_localstack/health | jq -e '.services.s3 == "running"' && \
        curl -s http://localhost:4566/_localstack/health | jq -e '.services.dynamodb == "running"' && \
        curl -s http://localhost:4566/_localstack/health | jq -e '.services.sqs == "running"'
      interval: 1s
      timeout: 10s
      retries: 10
      start_period: 5s
