[package]
name = "datadog-metrics"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
dogstatsd = { workspace = true }
once_cell = "1.19"
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
