name: CI

on:
  - pull_request

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Start LocalStack and wait for it to be healthy
        run: |
          docker compose up -d --wait localstack

      - name: Run tests
        run: cargo test -- --nocapture

      - name: Clean up
        run: docker compose down

  proto-check:
    name: Proto Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Check breaking changes
        working-directory: ./notification-worker
        run: buf breaking --against buf.build/xmtp/proto:main

  deny:
    name: Cargo deny
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check ${{ matrix.checks }}
          rust-version: stable

  build-docker-backend:
    name: Build and Test Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: false
          load: true
          tags: world-chat-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Start LocalStack and wait for it to be healthy
        run: |
          docker compose up -d --wait localstack

      - name: Run backend container
        run: |
          # Use the explicit network defined in docker-compose.yml
          docker run -d \
            --name world-chat-backend-test \
            --network world-chat-network \
            -p 8000:8000 \
            -e AWS_ENDPOINT_URL=http://localstack:4566 \
            --env-file backend/.env.example \
            world-chat-backend:latest

          # Wait for the application to start
          sleep 5

          # Output logs for debugging
          docker logs world-chat-backend-test

      - name: Health check Docker container
        run: curl -f http://0.0.0.0:8000/health

      - name: Clean up
        run: |
          docker stop world-chat-backend-test || true
          docker rm world-chat-backend-test || true
          docker compose down
