name: Daily job

#on:
#  schedule:
#    - cron: "0 3 * * *"
#  workflow_dispatch: {}

on:
  push:
    branches:
      - INFRA-5677/publish-docker-image
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  packages: write


jobs:
  run:
    runs-on:
      group: arc-public-large-amd64-runner
#    environment: prod
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          docker pull ghcr.io/worldcoin/world-chat-secure-enclave-signed-dev:secure-enclave-v2-6d989e651a6e7d3a72e107eb4c0e151ebd13ff44-5a54dafdbdd8fbb90778f3df272207b910989438
          docker images | head